2022-03-20 13:57:43,995 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x000001D29E68C670>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-20 13:57:44,106 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-20 13:57:53,638 INFO core.py Установлено соедение с ПК ('127.0.0.1', 54114)
2022-03-20 13:57:54,147 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647773873.6463044, 'user': {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5RBqcY39Fk46KJ0/eWa\n/QBOMASk3bD0j/dm8MTxIO9PGE7XPneat139rELczBQkgBmf0HFfQPcmuMiFH4Xs\nffcIy+o7XTq4pXamiZ0+EEWWE6YCHhGIkYdWiBzbT0OX1DvGcWPIMUFu78tmfPpE\nituG8c86WD/9qmKzJJWiGXuDCatlIBrq5roWdhVsVPokwKeKOm5rNb+0OFotWe+t\nue7roaoS8uuMI1jCo41zxtBGSfnc8eOw5pKsq/vI3F0I8tUY+U4ic6gKNvlyj/qc\nbbcIiEeaurkQ3XIIrh/jVmJeYCzsHmnFL3p9rJaG2UWVzEzKEzXteksaiwqtv63J\npwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 13:57:54,148 DEBUG core.py Start auth process for {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5RBqcY39Fk46KJ0/eWa\n/QBOMASk3bD0j/dm8MTxIO9PGE7XPneat139rELczBQkgBmf0HFfQPcmuMiFH4Xs\nffcIy+o7XTq4pXamiZ0+EEWWE6YCHhGIkYdWiBzbT0OX1DvGcWPIMUFu78tmfPpE\nituG8c86WD/9qmKzJJWiGXuDCatlIBrq5roWdhVsVPokwKeKOm5rNb+0OFotWe+t\nue7roaoS8uuMI1jCo41zxtBGSfnc8eOw5pKsq/vI3F0I8tUY+U4ic6gKNvlyj/qc\nbbcIiEeaurkQ3XIIrh/jVmJeYCzsHmnFL3p9rJaG2UWVzEzKEzXteksaiwqtv63J\npwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 13:57:54,154 DEBUG core.py Correct username, starting passwd check.
2022-03-20 13:57:54,157 DEBUG core.py Auth message = {'response': 511, 'bin': '424f1718530873feb27710c920e4a4ef34a8125917447055543f7ff36eba7ca71cfe802288598cf20f5c9a5798d75c619817bccc359757e91bc2accdab836dd3'}
2022-03-20 13:57:54,676 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647773874.1593153, 'account_name': 'user_100'}
2022-03-20 13:57:55,187 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647773874.704533, 'user': 'user_100'}
2022-03-20 13:58:07,386 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647773886.9381077, 'account_name': 'user_100'}
2022-03-20 13:58:07,387 INFO core.py Клиент ('127.0.0.1', 54114) отключился от сервера.
2022-03-20 13:58:09,984 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x000001D29E68C670>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
2022-03-20 13:58:28,065 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x0000022A2B2ADBA0>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-20 13:58:28,130 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-20 13:58:30,466 INFO core.py Установлено соедение с ПК ('127.0.0.1', 54203)
2022-03-20 13:58:30,779 INFO core.py Установлено соедение с ПК ('127.0.0.1', 54204)
2022-03-20 13:58:30,780 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647773910.4756444, 'user': {'account_name': 'user_0', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnReTRKMwR7h1mnDohIGo\nU233YeyINkzdl6LpA9efP9lV6ZvTX5Y0RRCK/cP4bmdAPMg97pV4KlSSgf9PtHYY\n64LPAXkhXnIkJpHDuLdRmxgxkp4pGUcfVgbsWo/HJoJXGaLJa7R9jKTDO/hiA9id\nD1+jRaAHrNl9HVY7caGUGCAQINl/IAGvkDq3KezzspWYuU+cbpC0dve52X5slHbx\nsNIHWZFWBylMmhGRkHPh0Tf95smBb7NOaW4RDcjiLW7wVgZ1GJjJGLz3vIOm8oQz\n0qptvN11I4dlzGHLFmMqd2rKWWx0GPejtcCqsdmeY7nf/ngcAFFJ605EFnaD+Cix\nEQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 13:58:30,780 DEBUG core.py Start auth process for {'account_name': 'user_0', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnReTRKMwR7h1mnDohIGo\nU233YeyINkzdl6LpA9efP9lV6ZvTX5Y0RRCK/cP4bmdAPMg97pV4KlSSgf9PtHYY\n64LPAXkhXnIkJpHDuLdRmxgxkp4pGUcfVgbsWo/HJoJXGaLJa7R9jKTDO/hiA9id\nD1+jRaAHrNl9HVY7caGUGCAQINl/IAGvkDq3KezzspWYuU+cbpC0dve52X5slHbx\nsNIHWZFWBylMmhGRkHPh0Tf95smBb7NOaW4RDcjiLW7wVgZ1GJjJGLz3vIOm8oQz\n0qptvN11I4dlzGHLFmMqd2rKWWx0GPejtcCqsdmeY7nf/ngcAFFJ605EFnaD+Cix\nEQIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 13:58:30,786 DEBUG core.py Correct username, starting passwd check.
2022-03-20 13:58:30,788 DEBUG core.py Auth message = {'response': 511, 'bin': '82e5a9da85632c8758d6fc8bc57b6db24165e8e703849147bab663b6389079772bebbebfdd12edd1b7292e1e88046df0f6b3acb9798a1de41f690180ac274233'}
2022-03-20 13:58:31,309 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647773910.7916605, 'account_name': 'user_0'}
2022-03-20 13:58:31,315 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647773910.8066616, 'user': {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwHgBSFXvr7Ef3hPy4Sa\nu/gbONCX6zVzmYkyG/SBrnGxvWD2xBOjNYalZpPYmvs1RqqU9RmH9ocb0f9FmAWw\nr0gowBEUSoQ+PTrDU8dsY9MjXK5qoEO/xSy40E/StdzFXWeuldwDQ+cqcWAG8BLd\nCKL1CTlv+vtrvepIjBVi4RiKqhtPH3eQGVEeBCSuCG9epTIsPwUQxBoAP/kwzcvc\nFiULZAdLyOY+daHV5x+gO6q4BfF/yu9fJrmnXbav69NRspcrvw2ahpUKOCd0bcft\ns5uhhjMtM3is7l8VAGIaDOYgo4eX+1W/mLomUYgZZCSDU1LPYwTlT4nUGQ4BEQuO\nCwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 13:58:31,315 DEBUG core.py Start auth process for {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwHgBSFXvr7Ef3hPy4Sa\nu/gbONCX6zVzmYkyG/SBrnGxvWD2xBOjNYalZpPYmvs1RqqU9RmH9ocb0f9FmAWw\nr0gowBEUSoQ+PTrDU8dsY9MjXK5qoEO/xSy40E/StdzFXWeuldwDQ+cqcWAG8BLd\nCKL1CTlv+vtrvepIjBVi4RiKqhtPH3eQGVEeBCSuCG9epTIsPwUQxBoAP/kwzcvc\nFiULZAdLyOY+daHV5x+gO6q4BfF/yu9fJrmnXbav69NRspcrvw2ahpUKOCd0bcft\ns5uhhjMtM3is7l8VAGIaDOYgo4eX+1W/mLomUYgZZCSDU1LPYwTlT4nUGQ4BEQuO\nCwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 13:58:31,317 DEBUG core.py Correct username, starting passwd check.
2022-03-20 13:58:31,318 DEBUG core.py Auth message = {'response': 511, 'bin': '49c0f6edaa9d8d9d3a2445801c8445f7ee0c13936d3637e1fd8c6346b1d63045a9fea7fd0c5e44531900110dd8ba1a880c8561c543cadc1b0423ebb611f378ab'}
2022-03-20 13:58:31,830 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647773911.3352122, 'user': 'user_0'}
2022-03-20 13:58:31,835 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647773911.3202243, 'account_name': 'user_1'}
2022-03-20 13:58:32,347 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647773911.8572686, 'user': 'user_1'}
2022-03-20 13:58:37,459 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647773916.9410305, 'account_name': 'user_0'}
2022-03-20 13:58:41,551 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_1', 'to': 'user_0', 'time': 1647773921.409825, 'mess_text': 'iPkW9kA1We1hZltc51DvZBRPFJ4SC1b3Hmup2EQPvmHIMn6DYC/shfx8x7gkhXq123fzmHsiHHjJ9yAEnTsIkahaBry4pUbR+bB92vuXZCcvmj8agTfGivrDmU+TdliEnYWEGUZNawRldLazhFmtEGs9J01UYIzJAQpV+j1fE1xGuaDF3UEp7eo4Z0x3Ls6eqamuISGKVdrPThiKFEiYsQ+eH3PjCCK6QQwkc0kYsSyMTlRfLHUuJTypyZl0QXZn4oZ/TeTlEDG+GcDGkOzGsXHoJLL7Hd4M5oE6g/LFXJbUnyQM0Z7utA/yOQjdBxQ9BfFacYryB5wfi4hhD7lkrQ=='}
2022-03-20 13:58:41,567 INFO core.py Отправлено сообщение пользователю user_0 от пользователя user_1.
2022-03-20 13:58:43,608 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647773923.3339014, 'account_name': 'user_1'}
2022-03-20 13:58:47,179 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647773927.130663, 'mess_text': 'gTtjkpuAI62yiz4IAGqR2SfAOMJaFn5w00JuzUq8Ytdu00cQfq/IAzw9Grt3AUYmgujh0m6y1DXy+SFL75mbXmc6mVhl0G/WnxsgIMrzrmt2YzNDN1/UHsDx3gJZoa1eSWB0lVRlNNY5Xmw9mdRMUuyooWbDNmLDLf4Anr5kNucfQtoTSgzWqH1srXd6nPt1xJufqbxL1AZm/uNQLBbiB2HdW4idYprLevaHsjhdHH7OcxIFZ9DGZ14Ir+SNFvlGdi4ke08Hp/ougf0tY9AnWOqGNfv150GGDQtFMERGyNLhfDj4xth+l4ypZ+QTMlthbqoOIHn++iwK2i1nvJrZFA=='}
2022-03-20 13:58:47,192 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 13:59:01,466 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647773941.2241664, 'account_name': 'user_1'}
2022-03-20 13:59:01,466 INFO core.py Клиент ('127.0.0.1', 54204) отключился от сервера.
2022-03-20 13:59:03,521 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647773943.1240742, 'account_name': 'user_0'}
2022-03-20 13:59:03,522 INFO core.py Клиент ('127.0.0.1', 54203) отключился от сервера.
2022-03-20 13:59:04,452 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x0000022A2B2ADBA0>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
2022-03-20 14:21:14,524 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x000001EA18B33730>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-20 14:21:14,584 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-20 14:21:22,800 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57267)
2022-03-20 14:21:23,310 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647775282.8270185, 'user': {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5RBqcY39Fk46KJ0/eWa\n/QBOMASk3bD0j/dm8MTxIO9PGE7XPneat139rELczBQkgBmf0HFfQPcmuMiFH4Xs\nffcIy+o7XTq4pXamiZ0+EEWWE6YCHhGIkYdWiBzbT0OX1DvGcWPIMUFu78tmfPpE\nituG8c86WD/9qmKzJJWiGXuDCatlIBrq5roWdhVsVPokwKeKOm5rNb+0OFotWe+t\nue7roaoS8uuMI1jCo41zxtBGSfnc8eOw5pKsq/vI3F0I8tUY+U4ic6gKNvlyj/qc\nbbcIiEeaurkQ3XIIrh/jVmJeYCzsHmnFL3p9rJaG2UWVzEzKEzXteksaiwqtv63J\npwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 14:21:23,310 DEBUG core.py Start auth process for {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5RBqcY39Fk46KJ0/eWa\n/QBOMASk3bD0j/dm8MTxIO9PGE7XPneat139rELczBQkgBmf0HFfQPcmuMiFH4Xs\nffcIy+o7XTq4pXamiZ0+EEWWE6YCHhGIkYdWiBzbT0OX1DvGcWPIMUFu78tmfPpE\nituG8c86WD/9qmKzJJWiGXuDCatlIBrq5roWdhVsVPokwKeKOm5rNb+0OFotWe+t\nue7roaoS8uuMI1jCo41zxtBGSfnc8eOw5pKsq/vI3F0I8tUY+U4ic6gKNvlyj/qc\nbbcIiEeaurkQ3XIIrh/jVmJeYCzsHmnFL3p9rJaG2UWVzEzKEzXteksaiwqtv63J\npwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 14:21:23,316 DEBUG core.py Correct username, starting passwd check.
2022-03-20 14:21:23,318 DEBUG core.py Auth message = {'response': 511, 'bin': '3929afc84926257bfef858ea948cbbaed74d229d8ed6a3780928d04d44a873ecd0a2cbf6565310c285ed67e075096f43136efff4441348f82064338cc2c2f07b'}
2022-03-20 14:21:23,847 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647775283.3210244, 'account_name': 'user_100'}
2022-03-20 14:21:24,354 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647775283.8723247, 'user': 'user_100'}
2022-03-20 14:21:27,919 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647775287.6082067, 'account_name': 'user_100'}
2022-03-20 14:21:27,919 INFO core.py Клиент ('127.0.0.1', 57267) отключился от сервера.
2022-03-20 14:21:30,279 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x000001EA18B33730>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
2022-03-20 14:22:42,003 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x0000020C56403730>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-20 14:22:42,052 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-20 14:22:47,340 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57467)
2022-03-20 14:22:47,844 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647775367.3661737, 'user': {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5RBqcY39Fk46KJ0/eWa\n/QBOMASk3bD0j/dm8MTxIO9PGE7XPneat139rELczBQkgBmf0HFfQPcmuMiFH4Xs\nffcIy+o7XTq4pXamiZ0+EEWWE6YCHhGIkYdWiBzbT0OX1DvGcWPIMUFu78tmfPpE\nituG8c86WD/9qmKzJJWiGXuDCatlIBrq5roWdhVsVPokwKeKOm5rNb+0OFotWe+t\nue7roaoS8uuMI1jCo41zxtBGSfnc8eOw5pKsq/vI3F0I8tUY+U4ic6gKNvlyj/qc\nbbcIiEeaurkQ3XIIrh/jVmJeYCzsHmnFL3p9rJaG2UWVzEzKEzXteksaiwqtv63J\npwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 14:22:47,845 DEBUG core.py Start auth process for {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5RBqcY39Fk46KJ0/eWa\n/QBOMASk3bD0j/dm8MTxIO9PGE7XPneat139rELczBQkgBmf0HFfQPcmuMiFH4Xs\nffcIy+o7XTq4pXamiZ0+EEWWE6YCHhGIkYdWiBzbT0OX1DvGcWPIMUFu78tmfPpE\nituG8c86WD/9qmKzJJWiGXuDCatlIBrq5roWdhVsVPokwKeKOm5rNb+0OFotWe+t\nue7roaoS8uuMI1jCo41zxtBGSfnc8eOw5pKsq/vI3F0I8tUY+U4ic6gKNvlyj/qc\nbbcIiEeaurkQ3XIIrh/jVmJeYCzsHmnFL3p9rJaG2UWVzEzKEzXteksaiwqtv63J\npwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 14:22:47,850 DEBUG core.py Correct username, starting passwd check.
2022-03-20 14:22:47,853 DEBUG core.py Auth message = {'response': 511, 'bin': 'c4effb3ce9f170737e5fdbdcbae56231d9fa3896705b434e9d8076036634557abb9bb5fbefcb0bbdf96d4a72fbcac9a5565b773539ed263ba4d0e4946863d456'}
2022-03-20 14:22:48,374 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647775367.8554573, 'account_name': 'user_100'}
2022-03-20 14:22:48,890 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647775368.397454, 'user': 'user_100'}
2022-03-20 14:22:52,444 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647775371.7038674, 'account_name': 'user_100'}
2022-03-20 14:22:52,444 INFO core.py Клиент ('127.0.0.1', 57467) отключился от сервера.
2022-03-20 14:22:54,152 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x0000020C56403730>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
2022-03-20 14:23:02,328 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x0000016ABF08CCA0>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-20 14:23:02,383 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-20 14:23:03,265 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57515)
2022-03-20 14:23:03,270 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57516)
2022-03-20 14:23:03,776 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647775383.2856731, 'user': {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwHgBSFXvr7Ef3hPy4Sa\nu/gbONCX6zVzmYkyG/SBrnGxvWD2xBOjNYalZpPYmvs1RqqU9RmH9ocb0f9FmAWw\nr0gowBEUSoQ+PTrDU8dsY9MjXK5qoEO/xSy40E/StdzFXWeuldwDQ+cqcWAG8BLd\nCKL1CTlv+vtrvepIjBVi4RiKqhtPH3eQGVEeBCSuCG9epTIsPwUQxBoAP/kwzcvc\nFiULZAdLyOY+daHV5x+gO6q4BfF/yu9fJrmnXbav69NRspcrvw2ahpUKOCd0bcft\ns5uhhjMtM3is7l8VAGIaDOYgo4eX+1W/mLomUYgZZCSDU1LPYwTlT4nUGQ4BEQuO\nCwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 14:23:03,776 DEBUG core.py Start auth process for {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwHgBSFXvr7Ef3hPy4Sa\nu/gbONCX6zVzmYkyG/SBrnGxvWD2xBOjNYalZpPYmvs1RqqU9RmH9ocb0f9FmAWw\nr0gowBEUSoQ+PTrDU8dsY9MjXK5qoEO/xSy40E/StdzFXWeuldwDQ+cqcWAG8BLd\nCKL1CTlv+vtrvepIjBVi4RiKqhtPH3eQGVEeBCSuCG9epTIsPwUQxBoAP/kwzcvc\nFiULZAdLyOY+daHV5x+gO6q4BfF/yu9fJrmnXbav69NRspcrvw2ahpUKOCd0bcft\ns5uhhjMtM3is7l8VAGIaDOYgo4eX+1W/mLomUYgZZCSDU1LPYwTlT4nUGQ4BEQuO\nCwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 14:23:03,782 DEBUG core.py Correct username, starting passwd check.
2022-03-20 14:23:03,784 DEBUG core.py Auth message = {'response': 511, 'bin': '0b0eb2e968bcca26d4d37dba56bb18a209f0c56f197a2c9849d350be1e7e2a385fbfe619de2d188165e581abd158c607104f1711d932518b65f4bc952aa1f1cb'}
2022-03-20 14:23:03,799 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647775383.2786741, 'user': {'account_name': 'user_0', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnReTRKMwR7h1mnDohIGo\nU233YeyINkzdl6LpA9efP9lV6ZvTX5Y0RRCK/cP4bmdAPMg97pV4KlSSgf9PtHYY\n64LPAXkhXnIkJpHDuLdRmxgxkp4pGUcfVgbsWo/HJoJXGaLJa7R9jKTDO/hiA9id\nD1+jRaAHrNl9HVY7caGUGCAQINl/IAGvkDq3KezzspWYuU+cbpC0dve52X5slHbx\nsNIHWZFWBylMmhGRkHPh0Tf95smBb7NOaW4RDcjiLW7wVgZ1GJjJGLz3vIOm8oQz\n0qptvN11I4dlzGHLFmMqd2rKWWx0GPejtcCqsdmeY7nf/ngcAFFJ605EFnaD+Cix\nEQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 14:23:03,799 DEBUG core.py Start auth process for {'account_name': 'user_0', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnReTRKMwR7h1mnDohIGo\nU233YeyINkzdl6LpA9efP9lV6ZvTX5Y0RRCK/cP4bmdAPMg97pV4KlSSgf9PtHYY\n64LPAXkhXnIkJpHDuLdRmxgxkp4pGUcfVgbsWo/HJoJXGaLJa7R9jKTDO/hiA9id\nD1+jRaAHrNl9HVY7caGUGCAQINl/IAGvkDq3KezzspWYuU+cbpC0dve52X5slHbx\nsNIHWZFWBylMmhGRkHPh0Tf95smBb7NOaW4RDcjiLW7wVgZ1GJjJGLz3vIOm8oQz\n0qptvN11I4dlzGHLFmMqd2rKWWx0GPejtcCqsdmeY7nf/ngcAFFJ605EFnaD+Cix\nEQIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 14:23:03,805 DEBUG core.py Correct username, starting passwd check.
2022-03-20 14:23:03,807 DEBUG core.py Auth message = {'response': 511, 'bin': '3d719412428c59f73e11c054aa23e3dc4d23f07dbef3fcd641265510638d8b031368bbd2d07b5f91ba24665d4d1347a9bd782b4044dcc71c1614b7903a8cbdca'}
2022-03-20 14:23:04,324 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647775383.786081, 'account_name': 'user_1'}
2022-03-20 14:23:04,331 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647775383.809081, 'account_name': 'user_0'}
2022-03-20 14:23:04,837 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647775384.3510802, 'user': 'user_1'}
2022-03-20 14:23:04,842 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647775384.357081, 'user': 'user_0'}
2022-03-20 14:23:14,986 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647775394.621651, 'account_name': 'user_1'}
2022-03-20 14:23:20,112 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775399.9515755, 'mess_text': 'Lb2uRr49eJ2BcHsEEflZtS6D5XDKmJv9FTFqCn7T5Y8nzQzEOiIwLqYfEMOeIqjd52CioGQXjK/SKcZp0Ev29m7NOMEQHcgPOvSFo1X6nBsMvW3RcaWsgsF3OjA8MbRUPlNXlCNWzso6r5ku+z6LCBCRTncC4Auuy2KynILosXvg0I4tpXPHlp2DpKsenV8PzqwZ7Jlg22KR1NYHSpnUDKNZGEjT4C3Y67TBAXWWmTVxP2VY/RlV+xrGpD0CmOFONHeBD/6a6dp3B9DfEsN/1UBOWp6DVvTnoEyMlr19RNcdywZSAa6tTDVWOtrVLkk2RAUfTd1HnBstnGG0xtPP+A=='}
2022-03-20 14:23:20,124 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:23:22,671 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647775402.247142, 'account_name': 'user_0'}
2022-03-20 14:23:24,715 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_1', 'to': 'user_0', 'time': 1647775404.4849827, 'mess_text': 'a/IG8GgoHqrYpbjIyWz0W2RGxmU2fjJaVTSOaWDG1SDNHoS1vTuia/5WtA+7KqNmm/fbBF8CaGUYvd5sAJzTrVjaZ4v3r0CaQXSeUk3OYSWfzrtClD5qsdyBWmkPn2S/OOLhXK53IaSG6RdW05/sIZy3kweB2U2fBgz5gY1yjuaPTd9lpxopxMSVPstMeFCy1PJftoHG03evEhnOSLG8LN6FwfGXs95kqbfJSm38dB6qWyv0f3uelL0BaNTwvunpAp+xAdlpc+vjIFQGuwIF/zCa4zPdLC9OF4XZbDP9IYgXhrNFTQv1KjpLiR8AAMdhOnsTWzoPuMvl5+bXy/x3pw=='}
2022-03-20 14:23:24,731 INFO core.py Отправлено сообщение пользователю user_0 от пользователя user_1.
2022-03-20 14:23:28,817 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775408.4499297, 'mess_text': 'bjnN+YSgegrBLWv//Dd8S6VDFNnQpid6ChaMipgGhfaKUhEfTXIDPNi9Vu2rf0tfgWlYT9LChrdK+skWQ5pDM5GvrSxyDzemh/qwk9QFRRB0gA6hUpLlYYJtw6deOUOmpHR0/ld+F8z9fMfUiLGtq5JjUgn3yDmp4I+coLUt2lYG1jvxPB7Yk8vvtuyEgw14hyv6+5+qpXbXEHeQpl3b0dUtI9I5JsS9HTS7Che+sXfifEn6AHdGn2sbt8mbYBjYbBsNCdm9esJl3vfaPHcZzF5D1cJsNLejzLb3iK6CyzTWLQxaALeHCC/WnFtwdAH5UfTPSf2JIvtlxzuRxZRJBA=='}
2022-03-20 14:23:28,832 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:23:31,387 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_1', 'to': 'user_0', 'time': 1647775410.8536286, 'mess_text': 'LqLqWsNlxOdeUHW3BcBUEp94xiI+RKfkT/61JZfgjBf7XEREJ6Op2YXU1CG2FpP+PD1D5NGqV64gNyOV9jbIwph7VZ3ql2QO963AsVzACOnD+wVNgaPNbXIEAkuwEijuAeu7UT67Y5rmso9TZY4C4D8KEhqTiCP5t/ZZxM3hj1yVc1P3lTy6TQV0L09z6lfFd/zlWzl1O/b7FTqqf/wv4G9hXpCLV/A56KPSZ0vtGNf3qi0xmaRUqnQL4gkTvu4qYoFstAGnlFdbkCj1DZugXVZwMpHzlAgtxVDDOVGbQk0xNvDn6/hmQLc2lHnIEFDDOput2XLlEgCXOzMVg4F7VQ=='}
2022-03-20 14:23:31,400 INFO core.py Отправлено сообщение пользователю user_0 от пользователя user_1.
2022-03-20 14:23:37,014 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775416.7936418, 'mess_text': 'H71GuiAHaHzNnr4454s+FbT9jsvlTnA1EVUv1TiEi+mEe3FakU/O3FAPIy+WOxSmE/N5IWuLVb5NZQepL6/nclr10wcEGlEWfr/5CJAh6VP5HbPNebXzFdfaY9nYrr37P6LeLBn7MWZ1Fu/z9GZZK/dbGK4wI0TI3LcY/bNOvg/E8iyagx5xmh3dswc6m5nNAQu9IqFz6/hpba5L+L2gOtW9rHVi/af2z5WW6B2ccskVhGygAUs6NyImce6P73Cu81cI9zNU3kRDm4P7BlevQxG/JJFSArZ4WYsXc4l9fk4LIGT4I8MzC66seFYM9hsSSFyXYnpZLv6zzH2EXqL/eA=='}
2022-03-20 14:23:37,024 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:23:39,069 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_1', 'to': 'user_0', 'time': 1647775418.84362, 'mess_text': 'eS69ygKGF0XAaWotKCF6gyWrsyANbV8UOaAGj0/5mjwoNmOM3U4PJ3rBXEpeEpZWIFMJwmu1te97m+VoYTXZceLCgGgpsPHXeI1ggsD/WwujqcpFCt2Q6l2UoIeBvSv4tcS+B8CiN5VHL18HS78V1P4+r8eLb6+fYL4au6Li8hywgsRkEygmf3pP5MhW5U0oGrIhkZMnygcUfgnniwr1sBIICeXdcA5wkudsPrq2ESNNcpwWsZopWPt5/mtaKs1az3psE/OgZryx3iTk8WnoGzVq+DqNpbNVO10yRfIznS7M0lZs2YN8NTdVwnczf1dnw8xWHYY9kkxv1oYCu6kfgg=='}
2022-03-20 14:23:39,080 INFO core.py Отправлено сообщение пользователю user_0 от пользователя user_1.
2022-03-20 14:23:41,118 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775420.61105, 'mess_text': 'DREvXZQ6Y/YsuZiAfQQ0fGiFXyYYDUjIg6IxEOlMUNbjcS5cZ4s93OZZW/Oy2ZO7AZ65KS+tjsifSXSJV1I3rgXaGQlbgfobvuKhGIkDST4soxuFMpC5nSmV1B9p30GjKEHWKMFXaAKWVKxVDDAXBONf+NjLXbE2msZW9WCac2hLEhKzJSh2+8GdAIdDJsZ8hBcdoij1jqbElp/KN6K1oy0FA/LMAxffawGkVgRnruSUH+1CoOxhYWV5H5KTPCw1SzhGIllrLbVM4+vE1+TZz8ELwWbqt+TKzmB2engg+OojgsbGv09CmDW2g/39KQZjnDx+yPXbviaNv/WliizTuA=='}
2022-03-20 14:23:41,130 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:23:42,660 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775422.3956404, 'mess_text': 'Ha3/OqYIU5wS/Khfm2SAYIPMQIGKkdiy6ucSNmpLRONyG+aIKBKLASgd8YYTBd2IhcVkqpmSoENZxb7pb13FnkIS+Q9cR0cNEKF9kAD/01kqZbzaGRHk6WNXpxzPwy69VBJcdxHhvmxNzHoQJkDBqXb7fGbV/VSnOUJvnB70doLd0MBatxMY6l47HQclTSWS5Rr+wnlwjUi2QHbx7cRBTDMHhfpzWAdiw8OtB1jmuwzA2k/wQCGLrp31ahkD9epfsNVx/zRcqMzEdd483u7YOeXHDOvYYfWPiGZiBJLtMFnleh0/nkbhQPwHpvu4u0Ka4bkciKZ9qbrKcBMYjxmPBA=='}
2022-03-20 14:23:42,672 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:23:45,723 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775425.2618754, 'mess_text': 'FZJHII3W+w+zMO3fx9VnjPABaXVTKSLDqfLrWhupf3cfrKp7QZzVV8GkvHr/gjnhZwkekfTMfc6E74zhfXiQrmR/NbnvIh3TuiXbuKeqyTj4wDosARDEstEbDOLgFFg37kiZV4tCY1VME0DHaS+ptfOOg7i4rt4tq8ufcxbYUIvku4S0vYADkMei4VP9QB0ijDmg0c1K3s/bnNPz5/fa5CJ/wj8EnL31IHv5ebrilMaQ24wwMM9VZBRVW5C6K5HZQjkb3jDUev088ATMMceQnO4TA2PpNndSAqALg/uBfeRsYg/O0dRH2qIjxl5fG0ebBCeMQSAheyOP2q9DUTR5MA=='}
2022-03-20 14:23:45,735 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:25:31,545 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x0000017A72F9CCA0>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-20 14:25:31,600 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-20 14:25:32,519 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57868)
2022-03-20 14:25:32,550 INFO core.py Установлено соедение с ПК ('127.0.0.1', 57869)
2022-03-20 14:25:32,551 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647775532.530906, 'user': {'account_name': 'user_0', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnReTRKMwR7h1mnDohIGo\nU233YeyINkzdl6LpA9efP9lV6ZvTX5Y0RRCK/cP4bmdAPMg97pV4KlSSgf9PtHYY\n64LPAXkhXnIkJpHDuLdRmxgxkp4pGUcfVgbsWo/HJoJXGaLJa7R9jKTDO/hiA9id\nD1+jRaAHrNl9HVY7caGUGCAQINl/IAGvkDq3KezzspWYuU+cbpC0dve52X5slHbx\nsNIHWZFWBylMmhGRkHPh0Tf95smBb7NOaW4RDcjiLW7wVgZ1GJjJGLz3vIOm8oQz\n0qptvN11I4dlzGHLFmMqd2rKWWx0GPejtcCqsdmeY7nf/ngcAFFJ605EFnaD+Cix\nEQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 14:25:32,551 DEBUG core.py Start auth process for {'account_name': 'user_0', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnReTRKMwR7h1mnDohIGo\nU233YeyINkzdl6LpA9efP9lV6ZvTX5Y0RRCK/cP4bmdAPMg97pV4KlSSgf9PtHYY\n64LPAXkhXnIkJpHDuLdRmxgxkp4pGUcfVgbsWo/HJoJXGaLJa7R9jKTDO/hiA9id\nD1+jRaAHrNl9HVY7caGUGCAQINl/IAGvkDq3KezzspWYuU+cbpC0dve52X5slHbx\nsNIHWZFWBylMmhGRkHPh0Tf95smBb7NOaW4RDcjiLW7wVgZ1GJjJGLz3vIOm8oQz\n0qptvN11I4dlzGHLFmMqd2rKWWx0GPejtcCqsdmeY7nf/ngcAFFJ605EFnaD+Cix\nEQIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 14:25:32,562 DEBUG core.py Correct username, starting passwd check.
2022-03-20 14:25:32,565 DEBUG core.py Auth message = {'response': 511, 'bin': '56e5c8d0cce673229f2b3b8e484c61df84730cce331598f01fb853501247f9c0dc7f33b9f2e82b1c3d8796d257c6749bf58bd052c725faf40813eff02578deeb'}
2022-03-20 14:25:33,082 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647775532.5689046, 'account_name': 'user_0'}
2022-03-20 14:25:33,085 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647775532.5589063, 'user': {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwHgBSFXvr7Ef3hPy4Sa\nu/gbONCX6zVzmYkyG/SBrnGxvWD2xBOjNYalZpPYmvs1RqqU9RmH9ocb0f9FmAWw\nr0gowBEUSoQ+PTrDU8dsY9MjXK5qoEO/xSy40E/StdzFXWeuldwDQ+cqcWAG8BLd\nCKL1CTlv+vtrvepIjBVi4RiKqhtPH3eQGVEeBCSuCG9epTIsPwUQxBoAP/kwzcvc\nFiULZAdLyOY+daHV5x+gO6q4BfF/yu9fJrmnXbav69NRspcrvw2ahpUKOCd0bcft\ns5uhhjMtM3is7l8VAGIaDOYgo4eX+1W/mLomUYgZZCSDU1LPYwTlT4nUGQ4BEQuO\nCwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-20 14:25:33,085 DEBUG core.py Start auth process for {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtwHgBSFXvr7Ef3hPy4Sa\nu/gbONCX6zVzmYkyG/SBrnGxvWD2xBOjNYalZpPYmvs1RqqU9RmH9ocb0f9FmAWw\nr0gowBEUSoQ+PTrDU8dsY9MjXK5qoEO/xSy40E/StdzFXWeuldwDQ+cqcWAG8BLd\nCKL1CTlv+vtrvepIjBVi4RiKqhtPH3eQGVEeBCSuCG9epTIsPwUQxBoAP/kwzcvc\nFiULZAdLyOY+daHV5x+gO6q4BfF/yu9fJrmnXbav69NRspcrvw2ahpUKOCd0bcft\ns5uhhjMtM3is7l8VAGIaDOYgo4eX+1W/mLomUYgZZCSDU1LPYwTlT4nUGQ4BEQuO\nCwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-20 14:25:33,087 DEBUG core.py Correct username, starting passwd check.
2022-03-20 14:25:33,088 DEBUG core.py Auth message = {'response': 511, 'bin': '5249457f761a5c731585785407277b14f8017d1d6d9d9867a53da40f018d0e49a909334b6dcf8468a66a09db429fdf05d25100772e1de106a41904fe72e849f5'}
2022-03-20 14:25:33,617 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647775533.1056771, 'user': 'user_0'}
2022-03-20 14:25:33,625 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647775533.0906775, 'account_name': 'user_1'}
2022-03-20 14:25:34,136 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647775533.6450903, 'user': 'user_1'}
2022-03-20 14:25:38,223 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647775538.094742, 'account_name': 'user_0'}
2022-03-20 14:25:42,336 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_1', 'to': 'user_0', 'time': 1647775542.004721, 'mess_text': 'ZLjvrzSZmps4bzW18QHnFsnpNNBNCg0tEwnHC2hxQPa84rcT0v/b3qqdG6778YSiN3ChdL/NeoO5VZ4CSLI2opNNgyhY59yvlGFljIQFKC62yhYKU6K0sh/cDlErrIe1JW03SwgYRcV606sm2oSH5bKfsvg/v79PnzMjV7gVl+b4Z+/F4Sv+coSOHShDS06frJzwg0QXSdtXqaFvDdPnSaNeMIUYfXe21/EbWGIaED0GSlreTgrp3/0BPIZR+XfL6Q/upFn2BDuAdgDqcMUi9RFi0cumv5Ui+MTSrzTYD4KTgrjH47ZMAnIAQYpIBCv1DcpSDzJCJXM+r7rb+N3xzw=='}
2022-03-20 14:25:42,349 INFO core.py Отправлено сообщение пользователю user_0 от пользователя user_1.
2022-03-20 14:25:43,350 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647775543.3489594, 'account_name': 'user_1'}
2022-03-20 14:25:45,391 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775544.8996944, 'mess_text': 'PDlR3/KZNed+yQlcd9mYsCLWadkQ6Ibit9gf6As29PjHudGo8VVQqrJoVcAW8l2xzUAZbRNTPwVG7+GZ6SS9bkW9eR9a7KLdKpfD7h3w8Pmiljf1StgJhf5D+ZGQRzDoKUvRhVke7Dxx3ElclTwIAq4M/0Bm2S6rU4jDo/CWzculMMkT7bZ1VXgAcRYe2zoPaxtGho0KiWt/WKL+SobdgUK+3bpUQmwa66nFBuURFyVhiz8ooBffNm5TwPnP73Kc3JJ2babibK7Wak/KFdugbKehC14dG6X2r+5JLWFrAU/X4Zck9M2vPJI24RTuUk8Qqm5pFcFIF6eUG0pylhYxhQ=='}
2022-03-20 14:25:45,405 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:25:48,981 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_1', 'to': 'user_0', 'time': 1647775548.5753763, 'mess_text': 'KcJ+OGcsVcT1h0fxTj21zvsuQiKhX51ZO9GmlIXE7JUMiU8FaFog+0HjvK5hO88bE9HYikJeSrTHgrVOgUvKZIjGJs7p95NPeQhRzCVvtUGyZaKm1I3kvl4l/LZd0f9YgbI0uBJv8v6sznfagNIjkrznIiwq7gJf2QmoOh4uh8PqdMAX3WS6n0+A0RXTbzPUeaGe2NjQD/dsYhAZd7pn7FznqPGW9qDzh1agtNFKWfQd+B+nF5AmQIssNkGmUqQXKiSsoRT/hDR+LIy+hqA01xHpIxXm6b+xxD/G9hCa72IlDQlOpn0RcpG4Xy3DwsTkolwIOsjFNxot0ADN3bCamg=='}
2022-03-20 14:25:48,996 INFO core.py Отправлено сообщение пользователю user_0 от пользователя user_1.
2022-03-20 14:25:52,589 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'user_0', 'to': 'user_1', 'time': 1647775552.0671477, 'mess_text': 'tgw1HK7VTEgNFz0/yKjMlgP6HaRpHQSc49G680qO6q0RqXyTcf+DODTJW/asWspvOgZxh0J3J5/kYPnJrEYqQgvSjjCzcj7lnrFbAab8KYXQCzRRShMoN6FDS1b7zpmZdg+AXUVsfzYDIW3FYnKhYPwSd+gMIzxPuz2MDVen/iS5Igi6xaSskbO8+qa2v0Nr9TwmjjDMFB/m1UF9NjzX5qRxXNioQDm+1oUeUKO185+L6TH4EjbvwQojXJVqmfbGEOdZsqi3X8b7/kaz08yEW/n+tKR/igzrOf3tMcvYRdidj45XhDB9jmaX+bfLmh05w1mYyAjyhHDYjqmxGiY+1A=='}
2022-03-20 14:25:52,602 INFO core.py Отправлено сообщение пользователю user_1 от пользователя user_0.
2022-03-20 14:25:56,680 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647775556.215223, 'account_name': 'user_1'}
2022-03-20 14:25:56,681 INFO core.py Клиент ('127.0.0.1', 57869) отключился от сервера.
2022-03-20 14:25:57,704 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647775557.2614408, 'account_name': 'user_0'}
2022-03-20 14:25:57,705 INFO core.py Клиент ('127.0.0.1', 57868) отключился от сервера.
2022-03-20 14:25:58,138 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x0000017A72F9CCA0>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
